version: "3.9"
services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - localhost
    networks:
      - my-network

  mysql-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: example_password
      MYSQL_DATABASE: sport_api
      MYSQL_USER: amal
      MYSQL_PASSWORD: amal
    networks:
      - my-network

networks:
  my-network:
     driver: bridge

